[tool.poetry]
name = "2025-p1-phoenix16987"
version = "0.1.0"
description = ""
authors = ["str"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.9"
flask = "<3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

